### PR TITLE
Change request to allow more characters in select

### PR DESCRIPTION
**Pull request by gringostar**
Changes:
- Changed select logic to allow more characters in 'value' part
- Added wildcards to select syntax, to accommodate searching by partial strings
- Updated readme to reflect actual implementation (alternatively the implementation should be changed to allow `<attribute>+/-`)

### CODE REVIEW

**Comment by gringostar** [comment]
Hi @langecode and @AllanHoejgaardJensen 

Have you had a chance to review this PR? 

Best regards
Niels

**Review by langecode — APPROVED** [review]
I think it looks good. Thanks for the contribution and the included clean ups. I will just let @AllanHoejgaardJensen have a few more day to take a look then I will merge.

**Comment by gringostar** [comment]
> I think it looks good. Thanks for the contribution and the included clean ups. I will just let @AllanHoejgaardJensen have a few more day to take a look then I will merge.

Hi
Do you think it is OK to merge this PR now?

**Comment by langecode** [comment]
@gringostar  I will make a release latest in the weekend. Thanks for othe contribution.

**Comment by langecode** [comment]
Published as [v1.0.3](https://github.com/openapi-tools/api-capabilities/releases/tag/v1.0.3) - sorry for the wait.

**Pull request merged**
